theme: jekyll-theme-slate
title: Welcome to my Profile! ~~~
description: Jacob Haskamps CV
Here's a sentence with a footnote. [^1]

[^1]: This is the footnote.thank you to Carolyn Stransky for the help in making this presentable!
